### ISSUE TITLE
Button Hover

### ISSUE THREAD

**Issue by IEdiong** [nofeesahdee/3-column-preview-card#1]

**Comment by IEdiong** [comment]
Hello, it seems that your **learn more** button text become invisible when hovered. A quick fix could be to remove the code block below, 

```
css
#sedan-btn {
    color: hsl(31, 77%, 52%);
}
```
you are removing this because the **CSS specificity** of the `#sedan-btn` selector is high compared to that of the `button:hover`, thus overiding the `color: white;` that you had set on the `button:hover`.

**Comment by nofeesahdee** [comment]
Thank you for pointing that out, i had to remove the transparent background and just scale it 
There was no way i could make the color visible on hover
